name: CI

on:
  pull_request:

jobs:
  build_android:
    name: Android - Test and Build
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Decode and Write Google Service Files
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > androidApp/google-services.json

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-android-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Run Unit Tests
        run: ./gradlew allTests

#      - name: Run Instrumented Tests
#        run: ./gradlew connectedAndroidTest

      - name: Build Android
        run: ./gradlew :androidApp:assembleDebug

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk

  build_ios:
    name: iOS - Test and Build
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Decode and Write Google Service Files
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 -d > iosApp/iosApp/GoogleService-Info.plist

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-ios-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

#      - name: Run iOS Tests
#        run: |
#          cd iosApp
#          xcodebuild test -project iosApp.xcodeproj -scheme debug -destination 'platform=iOS Simulator,name=iPhone 15'

      - name: Build iOS
        run: ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64
