name: CI

on:
  pull_request:

jobs:
  build_android:
    name: Android - Test and Build
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Decode and Write Google Service Files
        env:
          JSON_CONTENT: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          if [ -n "$JSON_CONTENT" ] && [ -n "${{ inputs.config-android-path }}" ]; then
            echo "Creating Android google-services.json at ${{ inputs.config-android-path }}"
            echo "$JSON_CONTENT" | base64 -di > "${{ inputs.config-android-path }}"
          else
            echo "Skipping Android google-services.json creation (secret or path not provided)."
          fi

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-android-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Run Unit Tests
        run: ./gradlew allTests

#      - name: Run Instrumented Tests
#        run: ./gradlew connectedAndroidTest

      - name: Build Android
        run: ./gradlew :androidApp:assembleDebug

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk

  build_ios:
    name: iOS - Test and Build
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Decode and Write Google Service Files
        env:
          PLIST_CONTENT: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
        run: |
          if [ -n "$PLIST_CONTENT" ] && [ -n "${{ inputs.config-ios-path }}" ]; then
            echo "Creating iOS GoogleService-Info.plist at ${{ inputs.config-ios-path }}"
            echo "$PLIST_CONTENT" | base64 -di > "${{ inputs.config-ios-path }}"
          else
            echo "Skipping iOS GoogleService-Info.plist creation (secret or path not provided)."
          fi  

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-ios-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

#      - name: Run iOS Tests
#        run: |
#          cd iosApp
#          xcodebuild test -project iosApp.xcodeproj -scheme debug -destination 'platform=iOS Simulator,name=iPhone 15'

      - name: Build iOS
        run: ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64
